//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AR2AP.BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AR2APContainer : DbContext
    {
        public AR2APContainer()
            : base("name=AR2APContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgencyEntity> AgencyEntities { get; set; }
        public DbSet<ClientEntity> ClientEntities { get; set; }
        public DbSet<AREntity> AREntities { get; set; }
        public DbSet<TeamEntity> TeamEntities { get; set; }
        public DbSet<EmpEntity> EmpEntities { get; set; }
        public DbSet<ARRelatedEmpEntity> ARRelatedEmpEntities { get; set; }
        public DbSet<CollectionEntity> CollectionEntities { get; set; }
        public DbSet<WriteOffEntity> WriteOffEntities { get; set; }
    }
}
