//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AR2AP.BLL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>客户实体</summary>
    public partial class ClientEntity
    {
        public ClientEntity()
        {
            this.AREntities = new HashSet<AREntity>();
            this.CollectionEntities = new HashSet<CollectionEntity>();
        }
        /// <summary>客户编号</summary>
        public short ClientID { get; set; }
        /// <summary>客户类型(直客/代理)</summary>
        public byte ClientType { get; set; }
        /// <summary>客户所属的集团</summary>
        public string ClientGroup { get; set; }
        /// <summary>客户名称</summary>
        public string ClientName { get; set; }
    
        public virtual ICollection<AREntity> AREntities { get; set; }
        public virtual ICollection<CollectionEntity> CollectionEntities { get; set; }
    }
}
