//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AR2AP.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientEntity
    {
        public ClientEntity()
        {
            this.AREntities = new HashSet<AREntity>();
            this.Collection = new HashSet<CollectionEntity>();
        }
    
        public int ClientID { get; set; }
        public ClientTypeEnum ClientType { get; set; }
        public string ClientGroup { get; set; }
        public string ClientName { get; set; }
    
        public virtual ICollection<AREntity> AREntities { get; set; }
        public virtual ICollection<CollectionEntity> Collection { get; set; }
    }
}
